### ISSUE TITLE
If the same password is given, then also it is telling that the password is changed.

### ISSUE THREAD

**Issue by smartnavdeep** [Ved-programmer/Login-System#19] opened 2020-10-23 13:15 UTC
# Hi Ved, Here is the problem :

![Change Password 10_23_2020 6_39_37 PM](https://user-images.githubusercontent.com/65970997/97007756-85744c80-155f-11eb-9800-9f07c607ccc5.png)

### In password change, if I give the same string, it should tell that I have to enter a new password.
```
Hope you will fix it
Regards,
Navdeep
```

**Comment by Ved-programmer** [comment] 2020-10-23 13:47
Sure, I will fix it by tomorrow :)

**Comment by smartnavdeep** [comment] 2020-10-23 13:48
Ok, so currently I'm not closing this issue, but when you fix it, please close this issue

**Comment by Ved-programmer** [comment] 2020-10-23 15:51
sure

**Comment by Ved-programmer** [comment] 2020-10-24 08:11
I hope the problem is solved now, please tell if you get any other problems. I am closing this issue now.

**Closed** 2020-10-24 08:11 UTC
